id: IF8ADE646
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:27:02+00:00'
last_modified: '2022-06-08T06:11:09.448034+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3569
  title: དཀྱིལ་འཁོར་གྱི་ཐིག་རྩ་དང་དྲི་བྱ་ཚོན་གྱི་དབྱེ་བ་སོགས་མདོར་བསྡུས་སུ་བཀོད་པ་
  author: ''
  base:
    0E55:
      image_group_id: I1KG3636
      title: ''
      total_pages: 40
      order: 1
      base_file: 0E55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
